### ISSUE TITLE
Force 30 fps instead of 60 (youtube)

### ISSUE THREAD

**Issue by arcaine2** [xbmc/inputstream.adaptive#13]
With Kodi 17 and current youtube plugin it's finally possible to go 1080p and higher, plus 60 fps. While it's great, older hardware, like nVidia ION (still being used) doesn't handle 60 fps h264 videos nicely with vdpau enabled. It would be great to have an option to limit playback or force 30 fps stream for such case. I already tried couple min and max bandwidth settings but it either pushes 720p/60 or 1080p/60, plus, there's no 30 fps stream to select if i switch "stream selection" to manual. Still Chrome with h264ify is able to play the same video with 30 fps if such limit is enabled.

**Comment by HptmHavoc** [comment]
I would vote for it. 
Had some similar troubles with a RPI1. 
Maybe it would even be better to be able to set the fps manually.
Though i have to admit that these are very old devices and i don't know whether it is too much effort to implement this features.

**Comment by peak3d** [comment]
Ok, will look at it

**Comment by CrazyCoder** [comment]
Same issue with ION, 30fps limit would be much appreciated, thank you.

**Comment by circulosmeos** [comment]
Yeah, it is a necessary feature: even with hw capable of 4k (ODROID-C2, for example) youtube's 1080p/720p 60 fps aren't played flawlessly for some reason. It would be great to be able to choose!
And congratulations for your work, @peak3d

**Comment by zkrx** [comment]
any update?

**Comment by peak3d** [comment]
plan is to pull whitelist / resolution change information from kodi.

**Comment by CastagnaIT** [comment]
i close this since talking with team devs they do not allow get resolution lists and/or whitelist by using IS interface
therefore the only way is to implement a proxy to remove these specific streams
but i also see that this has already been done in the youtube addon
