### ISSUE TITLE
Audio "partially" working

### ISSUE THREAD

**Issue by olavopeixoto** [xbmc/inputstream.adaptive#130]
Hi,
I have a film provider with HLS widevine DRM that is showing the following behaviour on my Shield TV / Fire TV:

1) I set the inputstream.adaptive settings to "manual"
2) start the film with lowest bandwidth and it works ok, video and audio.
3) resolution is too low so I change it to a higher one, then the audio is gone and I get video only.

3) If I change the resolution to a higher one but not too high, it may work with audio, but then if, for some reason, it buffers a bit the audio is gone again.

1) If I leave inputstream.adaptive setting to "auto" it starts the film in the highest resolution with video only, no audio.

I'm not sure if this is an issue in the add-on or in Kodi itself or even if it's platform dependent.
Please let me know what, if anything, I can provide to try to troubleshoot this issue.
The provider needs subscription and is geoblocked.

Thank you

**Comment by raoulbhatia** [comment]
I have some audio issues with some German movies from Studio Canal Germany that I'd like to stream via Amazon Prime as well.

Let me know if this is related and if there is any debug information that I can provide.

**Comment by peak3d** [comment]
@olavopeixoto debug log (without component logging enabled) is mandatory :-)

**Comment by peak3d** [comment]
@olavopeixoto Is this Live TV? Seems that seek pos after switch gets after now().

18:45:20.688 T:138936738896   ERROR: AddOnLog: InputStream Adaptive: Download https://drmvodstreaming01a.video.globo.com/r90_720/v0/ea/23/67/6375105_6716bffd9ee8a01a49919e0b3609212834538366/6375105-manifest.ism/dash/6375105-manifest-audio=128000-1764352.dash doesn't provide any data: invalid

This is the end of Audio

**Comment by olavopeixoto** [comment]
No, this is not Live it is a film (VOD).

Any idea why it could be invalid? This very same url plays fine if I use the native android player.
Also if I switch back to a previously working audio stream, shouldn't it play normally? it seems it crashes the audio renderer or something, but video stays fine.

**Comment by olavopeixoto** [comment]
Hi @peak3d, the issue still the same using the latest nightly (kodi-20180522-7bc0f452-master-arm64-v8a.apk). It has not been fixed.
I'll PM you the details so you can test yourself but this is a Brazilian service you'll need a VPN to Brazil in order to test it.

**Comment by olavopeixoto** [comment]
I found a similar issue with an open stream. If you try this url [https://streaming-live.rtp.pt/liverepeater/rtp1HD_FPS.smil/manifest.mpd](https://streaming-live.rtp.pt/liverepeater/rtp1HD_FPS.smil/manifest.mpd) using the manual bandwidth selection it will cut the audio once you change to a higher bitrate.
In addition, this url has a bigger issue as it only works for 1min in Kodi, it stops after that.

it works fine in VLC though.

Here is the manifest: [https://pastebin.com/FBYuFc1m](https://pastebin.com/FBYuFc1m)

The error in Kodi log:

```
02:51:39.366 T:123145544482816   ERROR: CCurlFile::Open failed with code 404 for https://streaming-live.rtp.pt/liverepeater/rtp1HD_FPS.smil/chunk_ctaudio_cfm4s_ridp0aa0br96000_cs66546038815_mpd.m4s|Referer=http%3a%2f%2fwww.rtp.pt%2fplay&acceptencoding=gzip%2c%20deflate&connection=keep-alive&seekable=0:
02:51:39.366 T:123145544482816   ERROR: AddOnLog: InputStream Adaptive: Download https://streaming-live.rtp.pt/liverepeater/rtp1HD_FPS.smil/chunk_ctaudio_cfm4s_ridp0aa0br96000_cs66546038815_mpd.m4s doesn't provide any data: invalid
```

**Comment by peak3d** [comment]
This stream must be run with inputstream.adaptive.manifest_update_parameter=full property because the provided timings are not correct (frame durations differ from real clock durations)

But: there has been an issue with the update of those segments -> changes are pushed.

**Comment by peak3d** [comment]
@olavopeixoto if its VOD manifest_update_parameter should not be used.
Unfortunately I'm unable to find your PM with account settings so reproduction is not possible for me.
