### ISSUE TITLE
Is there a way to buffer ahead?

### ISSUE THREAD

**Issue by peterpan192** [xbmc/inputstream.adaptive#141]
I know, there have already been issues regarding the buffering situation. 
However, the best time of the year has started (NBA Playoffs) and the NBA has changed their streaming system to MPEG Dash. 
My internet connection is very slow so that I cannot even stream the games on lowest quality. 
It would be so sweet if KODI was able to buffer ahead so that I could start the playback of games in the morning and watch them after work. 
Is there any workaround for me here?

**Comment by peak3d** [comment]
Unfortunately still no buffering implemented,

**Comment by glennguy** [comment]
duplicate
