### ISSUE TITLE
Mips compilation

### ISSUE THREAD

**Issue by blueprince10** [xbmc/inputstream.adaptive#179]
Is it possible to compile the source for Enigma2 Mips porcessor?

**Comment by JinRonin** [comment]
Most likely not. Also you will not be able to play drm protected content due to missing widevine support.

**Comment by mirh** [comment]
Widevine exists for mips. 
https://github.com/aomp/android_mediatek_frameworks/tree/master/av/drm/widevine/libwvdrmengine/level3/mips
