### ISSUE TITLE
Add support for webvtt subtitle

### ISSUE THREAD

**Issue by Sopor** [xbmc/inputstream.adaptive#183]
When using the great add-on `Retrospect` i don't get any subtitle on every channel because they are now using `webvtt` instead of `srt`. The author of Retrospect told me this was the right place to ask for this and now i'm here :)

**Comment by basrieter** [comment]
To clarify this: I use the inputstream.adaptive add-on to play the `m3u8` and `mpd` streams. For `mpd` the  subs work just fine, for `m3u8` they are not detected.

**Comment by JinRonin** [comment]
Are both using webvtt or m3u8 only?
Just in case,  can you please provide debug log and content of the m3u8/mpd.

**Comment by basrieter** [comment]
The M3u8 contains the url to the webvtt which contains multiple parts. I will try to find a log file tonight.

**Comment by JinRonin** [comment]
Guess log is not needed but the content of your m3u8.

Here are some samples with webvtt that can probably be used to add webvtt support.

`https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8`
taken from https://developer.apple.com/streaming/examples/

`http://cdnbakmi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8`
taken from https://knowledge.kaltura.com/webvtt-and-hls-captions-support

Subtitles are not shown with and without inputstream adaptive.

**Comment by basrieter** [comment]
Here is an actual stream: https://cmoreseusphlsvod24.akamaized.net/vod/895d4/yczgd1wzscy(3911406_ISMUSP).ism/yczgd1wzscy(3911406_ISMUSP).m3u8

it contains a link to a m3u8 with webvtt parts: https://cmoreseusphlsvod24.akamaized.net/vod/895d4/yczgd1wzscy(3911406_ISMUSP).ism/yczgd1wzscy(3911406_ISMUSP)-textstream_swe=1000.m3u8

I think this stream should be playable from all regions

**Comment by orfeous1** [comment]
Maybe i do not understand. But any updates on WebVTT support in the inputstream addon?

**Comment by gizmocuz** [comment]
@orfeous1,

I think this has to do with the following line:

https://github.com/peak3d/inputstream.adaptive/blob/b76c81fc4c2d7fd02e73c1d0091ae190351fc2fa/src/parser/HLSTree.cpp#L123

It will currently only accept audio types here

Not sure if this is done on purpose....

**Comment by Snaah** [comment]
Another user of  Retrospect here, which uses the awesome InputStream Adaptive add-on. Is there by any chance some work in progress or plan to implement this? Would be great to have InputStream Adaptive being able to handle webvtt subtitles.

**Comment by CastagnaIT** [comment]
this has been fixed,
on Nexus now there is full webvtt support
