### ISSUE TITLE
[MPD] subtitles streams not added to player

### ISSUE THREAD

**Issue by pinoelefante** [xbmc/inputstream.adaptive#188]
Hi @peak3d 
I have an issue with my addon. Kodi is not showing the subtitles for the contents anymore.
I don't know if is a problem of inputstream or a mpd problem.
This is an example of mpd with subtitles: [11455893_HD.mpd](https://voddashhttps.cb.ticdn.it/videoteca2/V3/SerieTV/2017/09/50692870/DASH/11455893/11455893_HD.mpd)

(Audio/video works)

Tested with Kodi 18 Beta2

**Comment by pinoelefante** [comment]
full debug log: https://pastebin.com/EcAt1L2C

**Comment by CastagnaIT** [comment]
@pinoelefante are you able to provide a new mpd manifest for the subtitle problem? the link is broken

**Comment by pinoelefante** [comment]
@CastagnaIT i can't provide a new mpd. I don't have an active subscription
