### ISSUE TITLE
Inputstream fails due to wrong file request

### ISSUE THREAD

**Issue by Linkinsoldier** [xbmc/inputstream.adaptive#191]
I just updated my wetek play 2 to the latest libreelec alpha build (005) and tried to open Inputstreams from Amazon, Sky, Maxdome. Every single one of them failed - with the old widevine file (working before update) and the most recent one (Downloaded via inputstream.helper).

In the log i find this (example):
`09:36:09.161 T:3526718320  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.27.0
09:36:09.341 T:4092997648  NOTICE: VideoPlayer::OpenFile: /storage/Amazon/TV/Brooklyn Nine-Nine/Brooklyn Nine-Nine - S01E01 - Wir fangen Verbrecher und sehen gut dabei aus.strm
09:36:09.350 T:3339072368  NOTICE: Creating InputStream
09:36:09.351 T:3339072368   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.1.8
09:36:09.352 T:3339072368   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
09:36:09.352 T:3339072368   ERROR: CVideoPlayer::OpenInputStream - error opening [/storage/Amazon/TV/Brooklyn Nine-Nine/Brooklyn Nine-Nine - S01E01 - Wir fangen Verbrecher und sehen gut dabei aus.strm]
09:36:09.352 T:3339072368  NOTICE: CVideoPlayer::OnExit()`

so I guess (correctly) the issue is due to this line:
`Could not locate inputstream.adaptive.so.2.1.8`

So i fixed it by copying inputstream.adaptive.so.2.2.27 to inputstream.adaptive.so.2.1.8, but I hardly believe this is the way it should be :)

can I do anything more to help you fix this bug?

**Comment by Linkinsoldier** [comment]
since i updated to the latest libreelec both of them are no longer there and only the newest one (2.2.36 as far as i recall) exists and it still works i think this is solved!

**Comment by glennguy** [comment]
Issue is not within inputstream.adaptive
