### ISSUE TITLE
Missing audio track if "Stream Selection: Manual" is chosen

### ISSUE THREAD

**Issue by Varstahl** [xbmc/inputstream.adaptive#192]
While working on [Amazon VOD](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test) several users [notified the inability to manually select audio tracks](https://github.com/Sandmann79/xbmc/issues/145), reporting them available in only 2 out of the 9 languages that should have been available.

Investigating the issue I noticed that the amount of audio tracks in manual is cut at the exact number of audio tracks available with the reduction provided in Auto. A bit of data:

* [MPD in question](https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$fZxsbdx-yIU1TWj_ofY7pk1YwP8~/5b72/c23a/7f08/4d90-8490-2e27a0505b8a/08ed99f4-a079-4bb1-a80e-5e751335f06d_corrected.mpd)
* [Beautified MPD with stripped segment data](https://pastebin.com/CtHzguCQ)
* Auto selection audio streams (17 tracks):
  * German (DD+, AAC)
  * English (DD+, AAC)
  * Spanish (DD+, AAC)
  * Latin america spanish (DD+, AAC)
  * French (DD+, AAC)
  * Italian (DD+, AAC)
  * Polish (AAC)
  * Portuguese (DD+, AAC)
  * Turkish (DD+, AAC)
* Manual selection audio streams (17 tracks):
  * German (4 DD+, 9 AAC)
  * English (4 DD+)

I'm unsure when this started, but the first mention of the issue I could find is July 3.

**Comment by JinRonin** [comment]
As far as i know (from other conversations) there wont be any fixes for manual selection.
Its main usage was more or less for testing purposes and will probably be stripped sooner or later.

**Comment by Varstahl** [comment]
Ah, I see. I wanted to look into the matter myself, it sounds like a pretty easy fix, but if they want to strip it it makes no sense then.

**Comment by glennguy** [comment]
Fixed in Kodi 19 (kodi 18 has a hard limit of 32 streams for inputstream addons)
