### ISSUE TITLE
Feature Request: backport CDM 10 support to Krypton branch

### ISSUE THREAD

**Issue by stsichler** [xbmc/inputstream.adaptive#193]
Hi Peak3d,
could you please merge your commits <https://github.com/peak3d/inputstream.adaptive/commit/9035e42907c8d68e8e3e130f6592c3ddc13feec2> and <https://github.com/peak3d/inputstream.adaptive/commit/deea762ec95a9bc205d802a525c9210513939cd2> into the Krypton branch?
That would be VEEEERY nice! :)
**It merges without any conflicts** and voilà, Krypton again supports the current Widevine binary. I've successfully tested this with the one from ChromeOS 10718.88.2 recovery image (armhf).

And yes, I know that you Kodi developers (Thanks for your brilliant work!) currently strongly focus on Leia, but please keep in mind that Krypton might still be the release in use by most users and that there might be several people (...like me...) that are currently simply unable to update to Leia, especially on some rarer platforms.

**Comment by Hollol** [comment]
Actually, I am facing the same problem as stsichler (need to play DRM content on KODI and at moment unable to update to Leia development branch). Therefore I would be also very thankful, if the above mentioned commits could be merged into the Krypton branch of the inputstream addon and make CDM10 work in Krypton as well. 
Thanks @peak3d in advance.

**Comment by Hollol** [comment]
@stsichler, I guess you now have an inputstream.adaptive addon version with CDM10 support for Krypton at hand, right? Would it be possible to share this one until there will be (hopefully) an update to the official addon for Krypton? Thanks, Lars

**Comment by Hollol** [comment]
@stsichler, Thank you very much. My platform is a RPI2 with Libreelec 8. Since the RPI2 is an armhf platform too, the binaries might work. I will give it a try this evening and report back.

**Comment by stsichler** [comment]
oh, the file name of the ZIP is a typo. it is 2.0.20.

**Comment by Hollol** [comment]
So I tested it now. The binary is ok, but unfortunately I am still not able to play DRM content. Eroor message still "InputStream Adaptive: License update not successful (no keys)". Maybe I have the wrong libwidevine version (I am having the latest one).

**Comment by stsichler** [comment]
please mail me to Steevee28@web.de.
