### ISSUE TITLE
Getting cookie value back to addon

### ISSUE THREAD

**Issue by olavopeixoto** [xbmc/inputstream.adaptive#198]
Is it possible to get a cookie value set during the playback back into my addon?
I have an use case that if I don't provide the current session value back to the provider when attempting to play another video it will think I'm starting a new session and eventually it will block my access due to too many concurrent access.

**Comment by JinRonin** [comment]
That block sounds legit to me

**Comment by olavopeixoto** [comment]
I am using the very same auth token so it is in fact the same "session" but without the "lock session" from the playback the service has no way to know I stopped the previous video without waiting for the timeout.
It is legit for me to play how many videos I want as long as they are not concurrent.

**Comment by matthuisman** [comment]
Could you make a request to the url first via the add-on to get the session cookie.
Then send this when you play the video (so it uses it and not generate a new one).

eg. 
```
import requests
from urllib import quote

r = requests.get(media_url)
cookies = r.cookies.get_dict()
media_url += '|Cookie='
for key in cookies:
    media_url += '{}%3D{}; '.format(key, quote(cookies[key]))
```

**Comment by olavopeixoto** [comment]
It is not possible because the cookie is updated every 5min or so during playback.

**Comment by glennguy** [comment]
Could you make the request after playback has stopped to get the cookie and send the appropriate callback to the service to say you've stopped playback? You'd need to set up your own xbmc.Player class with the OnPlayBackStopped callback, rather than using setResolvedUrl.

**Comment by olavopeixoto** [comment]
Every request needs the last cookie value in order to proper authenticate, this value changes every 5min or so, I won't be able to do a last request without knowing the last cookie value in first place.

**Comment by glennguy** [comment]
@olavopeixoto did you ever get around this? Can we close the issue?

**Comment by olavopeixoto** [comment]
My work around so far is the same solution I use to solve https://github.com/xbmc/inputstream.adaptive/issues/184,
I am using a proxy server on my python addon to do the actual request and inputstream requests to this proxy instead.
So the issue still there, it is just a work around but very inefficient and one more code to maintain.
ps: as a side note the proxy code I am using does not seem to work properly on kodi matrix once ported to python 3. It works fine on leia using python 2 though.

**Comment by CastagnaIT** [comment]
Currently the kodi core does not have a way for a communication through different add-ons,
and there is currently no planning to implement this functionality in kodi core (maybe someone will one day)
even if ugly the only workaround is to use a proxy as you already done

I close the issue because it is not possible to do anything else
