### ISSUE TITLE
Crash on Android if WVCdm version is v5.1.0-android instead of v1.0

### ISSUE THREAD

**Issue by azbesthu** [xbmc/inputstream.adaptive#202]
Kodi 18 beta5 is crashing while it tries to initiate drm session if WVCdm has version "5.1.0-android". Also it is the same with beta1.

>2018-11-01 02:11:24.175 849-4461/? I/WVCdm: L3 Initialized. Trying L1.
>2018-11-01 02:11:24.175 849-4461/? W/WVCdm: Could not load liboemcrypto.so. Falling back to L3.  dlopen failed: library "liboemcrypto.so" not found
>2018-11-01 02:11:24.175 849-4461/? D/WVCdm: CryptoSession::Open: Lock: requested_security_level: Default
>2018-11-01 02:11:24.178 849-4461/? W/WVCdm: DeviceFiles::RetrieveHashedFile: /data/mediadrm/IDM1013/L3/cert.bin does not exist
>2018-11-01 02:11:24.179 849-4461/? I/WVCdm: L3 Terminate.
>2018-11-01 02:11:24.180 27485-27485/org.xbmc.kodi I/MediaDrm: Drm event (1,0)
>2018-11-01 02:11:24.272 27485-27675/org.xbmc.kodi A/zygote: java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: JNI GetArrayLength called with pending exception android.media.NotProvisionedException: Failed to open session
...

Happens on Xiaomi Mi A2 Oreo 8.1 (Android One device). 
Also reproducible with this 8.1 /  WVCdm v5.1.0-android simulator image that contains libhoudini for ARM compatibility: https://www.videomap.it/forum/viewtopic.php?f=25&t=1861 

It does not happen with Oreo 8.1 on Vernee Thor (MadOS) that has WVCdm 1.0. So maybe every Android environment can be affected if it has different version than 1.0.

Google's ExoPlay Demo app works fine on both versions
https://google.github.io/ExoPlayer/demo-application.html
Kaltura Device Info provision test succeeds on both.

#### Logs can be found here:
https://drive.google.com/drive/folders/1wwSfZIWvg7Hcx_rHm5byYzLrX4o3ntIL

Link contains:
- full kodi debug logs from both devices
- Kaltura Device Info drm version logs, screenshot 
- logcat crash log for A2 and working log for Thor.
- debug build of ExoPlayer Demo

**Comment by azbesthu** [comment]
I just saw something that maybe reated to this problem in one of the ExoPlayer tickets
https://github.com/google/ExoPlayer/issues/4772

I'm not sure if it is Androdi version or Drm version related. Maybe it is a different issue with Pie, but maybe the same logic is missing for this case:

>Devices need to be provisioned with a DRM Certificate. This DRM certificate is used by the license server to verify the device. Previously, there was one DRM certificate on the device, so any application could provision for the whole device.
Now, each application, or origin, will have a separate DRM Certificate. If you change the application package you should expect a new "needs provisioning" exception.

They also wrote a sample logic for handling the problem.

**Comment by DarkAnakin** [comment]
I don't think the provisioning issue can be resolve by this library. 
I had the same issue with my app when I upgrade my phone to lineageos 15.1 (android 8.1). To resolve it I had to provision the device first with the lauching and playing a video with the official provider app.

But it seems that change with Android 9.0 as you quoted, each package need to provision when requested so kodi app has to do it by itself.

I don't know how provisioning work but I tried to replicate what the official app has done without success. There no external request all the provisioning has been done locally.

**Comment by peak3d** [comment]
Is this issue still present? There have been changes in the last couple of days regarding provisioning.

**Comment by alexprimaid** [comment]
@azbesthu  i can't install it on android phone. Im using kodi rc 1. Do you install it on android phone?

**Comment by peak3d** [comment]
@alexprimaid what is "it" ?

**Comment by azbesthu** [comment]
Also working fine for me in Kodi 18.0 release version on Mi A2 updated to Android 9.
