### ISSUE TITLE
wrong audiotrack for german stream

### ISSUE THREAD

**Issue by M2k80** [xbmc/inputstream.adaptive#203]
i am not really sure, if that is an amazon plugin problem or inputstream problem.

if there is no german dd+track, the english dd+ track is choosen instead of german aac track.

to replicate  - with the amazon plugin try to play pjmasks - its a kid series.
in audio settings i can see : 
1. aac 2.0 german
2. aac 2.0 german
3. dd+ 5.1 english
4. aac 2.0 english
5. aac 2.0 englich
if my kodi is set to german, shouldnt be german language prefered first, then the best audio track?

**Comment by mirh** [comment]
That looks an awfully lot like my issue at https://github.com/Sandmann79/xbmc/issues/122
So better if you close here

**Comment by glennguy** [comment]
@M2k80 still an issue? Is it inputstream.adaptive related? Can we close?

**Comment by M2k80** [comment]
i closed it, if i see this problem again, i will open a new ticket
