### ISSUE TITLE
 Add-on 'inputstream.adaptive' is not compatible with Kodi

### ISSUE THREAD

**Issue by jodett** [xbmc/inputstream.adaptive#209]
Hello could someone tell me which version is compatible with kodi18rc1?
i built in archlinux following aur:
https://aur.archlinux.org/packages/kodi-pre-release/
i guess from that source:
https://github.com/xbmc/xbmc/tree/18.0rc1-Leia

i tried severall versions of inputstream-adaptive:
2.3.11
2.3.10
2.3.8
2.2.28
2.1.13

none is working
either they don't build because of missing types or all the newer ones say
`Add-on 'inputstream.adaptive' is not compatible with Kodi `
when trying to activate it in kodi

**Comment by jodett** [comment]
alright found the problem, besides installing 
'kodi-pre-release'
 i had to install 
'kodi-dev-pre-release'
and i had to delete kodi-dev which i guess installed older header files and therefore the addon was built with false references

**Comment by FloridaStream** [comment]
don't working here too :/

**Comment by dagwieers** [comment]
Is this issue still relevant ? If not, please close.

**Comment by bigretromike** [comment]
installed kodi (19.0+git20190807.0203-2b14719-0disco)
installed kodi-inputstream-adaptive_2.3.22-1~disco_amd64.deb
```
ERROR: Add-on 'inputstream.adaptive' is not compatible with Kodi
```
Any ideas, is 2.3.22 not compatible with matrix?
