### ISSUE TITLE
Segmented subtitles compatibility? 

### ISSUE THREAD

**Issue by filigran** [xbmc/inputstream.adaptive#221]
Hi!
Not sure how to describe this issue as I'm not really up to speed as to what this addon does, and how it helps with this issue, but here goes.

I'm using the retrospect addon to watch streams from play sites, but on one channel (swedish tv4) they use segmented vtts (subtitles). The dev of retrospect says this cannot be fixed by him, it could however be done by this addon.

See this thread/issue for examples and responses by dev (scroll to end, old issue):
https://bitbucket.org/basrieter/xbmc-online-tv/issues/954/tv4-play-seem-to-have-changed-their-api

Can this be done? 

Let me know if you need any more info!

Regards,
Thomas

**Comment by glennguy** [comment]
Inputstream.adaptive now supports this
