### ISSUE TITLE
media_renewal_url for HTTP status code 401

### ISSUE THREAD

**Issue by flubshi** [xbmc/inputstream.adaptive#226]
Hi peak3d,

I am currently working on creating a pvr plugin for the german tv stream provider waipu.tv
I noticed that a running stream is stopped three hours after the passed token was generated and a 401 HTTP status code is returned, because the token is expired. This raises two questions:

**First problem:**
Currently, the _inputstream.adaptive.media\_renewal\_url_ option is limited to 403 HTTP status code:
https://github.com/peak3d/inputstream.adaptive/blob/71be2d9b0a0c3a3c1c411cebff08caa368330fdd/src/main.cpp#L354
Is it possible either to add the 401 HTTP status code to this condition or to add an option to set the renew-status-code dynamically while setting the stream options? e.g. _inputstream.adaptive.media\_renewal\_http\_code_ 

**Second problem:**
How to implement this for a pvr plugin?

**Comment by peak3d** [comment]
@flubshiI I only see the option that you implement an tcp server either in binary pvr addon or a separate python service addon (bundled with your pvr addon) which proxies the license request. The license renewal impl. in inputstream.adaptive was a workaround, IMO the proper solution would be the proxy.

For example netflix addon uses such an license request proxy.

**Comment by glennguy** [comment]
@flubshi the workaround code mentioned has been removed, are we able to close this issue now?

**Comment by flubshi** [comment]
I will close this and check later. Thanks!
