### ISSUE TITLE
Ability to retry downloading the stream url

### ISSUE THREAD

**Issue by billythekids** [xbmc/inputstream.adaptive#234]
Hi,
I'm currently working with my addon using inputstream.adaptive.
i notice that inputstream is already able to resolve the effective url but when it tried to open the stream it returns 404 status.
Actually the issue here is the server is setting up little tricky, the url only works after several hit attempt

playlist
`https://hls3.imacdn.com/hls/d1782ef697dd276f72064d03ec56ea40/d1782ef697dd276f72064d03ec56ea40.playlist.m3u8`
One of the stream
`https://hls3.imacdn.com/drive//mnt/data/hls/30d66b432092ae7ec6623f2435f7676f/30d66b432092ae7ec6623f2435f7676f.m3u8`

How can i set the number of retry before it marks as disabled ?

Many thanks.

**Comment by glennguy** [comment]
@billythekids still having this problem? If not can we close the issue?

**Comment by CastagnaIT** [comment]
Closed due to no answer from author
