### ISSUE TITLE
Thread hammering when minimumUpdatePeriod = 0 and update_parameter_ != empty 

### ISSUE THREAD

**Issue by gizmocuz** [xbmc/inputstream.adaptive#235]
When a manifest specifies an minimumUpdatePeriod="PT0S" and the update_parameter_ is non-empty,
the AdaptiveTree::SegmentUpdateWorker() is hammering (causing a deadlock)

Solution could be to check this AdaptiveTree::StartUpdateThread()
(or the thread itself)

**Comment by glennguy** [comment]
fixed in #684
