### ISSUE TITLE
Question: inputstream is ready for new WV CDM11 API?

### ISSUE THREAD

**Issue by FloridaStream** [xbmc/inputstream.adaptive#248]
Is the inputstream.adaptive ready to receive the new wv API? This is a good question because with the arrival of the new API the inputstream could stop working with the addons.

There is some chance that the inputstream will be updated in the next few months to continue working in the future with the deactivation of obsolete APIs, because one hour the APIs 9 and 10 will be obsolete. @peak3d @liberty-developer @asciidisco

I tried to make an update to api 11, but it did not work, I bumped into RequestCdmProxy. I also noticed some outdated information in the cdm api of the inputstream that could be updated as well.

Ref:
https://chromium.googlesource.com/chromium/src/media/+/master/cdm/
https://chromium.googlesource.com/chromium/cdm/+log

**Comment by sandsmark** [comment]
where did it fail for you? RequestCdmProxy is just for communicating with hardware DRM stuff, isn't it?

I was a bit bored so I just pulled in the new API and made it build, but I haven't tested it (I don't have kodi or anything set up):
https://github.com/sandsmark/inputstream.adaptive/commits/master 

FWIW firefox is not on the new API either, so I doubt 11 will be mandatory very soon at least.

**Comment by peak3d** [comment]
@sandsmark very cool, I'll try how it works, thx for contributing!

**Comment by sandsmark** [comment]
if it doesn't work, you should try to just cherry-pick https://github.com/sandsmark/inputstream.adaptive/commit/6684d03f4575add659fd74b0c0afab1a71d9effd I guess, as the other refactoring-ish stuff I did might have broken something unintentionally.

**Comment by peak3d** [comment]
@sandsmark I pushed a PR into master branch which includes API 11 and some other code refactorings.
Thx for your ideas / support nevertheless.

I have issues using the current stable v10 32-bit windows widevine from chrome browser (4.10.1303.2) b.t.w. it segfaults unreproducable somewhere inside libwidevine. The one from chromium runs stable (4.10.1146.0), Any ideas?

**Comment by sandsmark** [comment]
I'm not sure, but I'd try to build with ubsan (fsanitize=undefined), and maybe asan, and see if it flags anything outside of libwidevine (mismatched data types, uninitialized memory, etc.). in case you haven't used it, basically just add `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined")` to the cmakelists.txt i the easiest, I guess (assuming you use clang or gcc).

if that doesn't show anything I guess the best is to just add log statements to every callback from libwidevine and see if anything looks unexpected, and if even that doesn't work instrument chromium as well to diff the calls it does against that.

I don't have any setup to test myself, but feel free to upload logs and I can help you look through them.
