### ISSUE TITLE
Kodi v18.x (LibreELEC) on NanoPC-T4 (RK3399)

### ISSUE THREAD

**Issue by XxAcielxX** [xbmc/inputstream.adaptive#251]
Hi,

I'm moving from RPI3 this new powerful RK3399 based board NanoPC-T4, but the issue I'm having is your InputStream_Adaptive won't install at all. As soon as I install it, it shows *Installation failed*.

Can you please look into this. Regards~

**Comment by peak3d** [comment]
log file pls.
