### ISSUE TITLE
[Info Request] Av1 video codec

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/inputstream.adaptive#262]
Netflix is introducing the firsts video codec profiles av1,
I have not yet verified if there are actually already videos with this codec
but they're sure to start soon, and i want to add it to the netflix addon if it is practicable

Are you planning to introduce support for the av1 codec?

**Comment by peak3d** [comment]
I guess netflix will provide it in mp4 container, so it should not be much work to implement.
Do you already have an example link?

**Comment by CastagnaIT** [comment]
I will do tests over the weekend and i refer to you

**Comment by CastagnaIT** [comment]
at this moment i have not been able to find videos with av1
I'll put it on standby
I will try to find again next month
when i have news, i'll let you know

**Comment by CastagnaIT** [comment]
i close this issue
currently ntfx web APIs are seem not yet enabled to get AV1 streams although the profile is already predisposed
developments on this codec are progressing too slowly (on ntfx side)...

**Comment by quietvoid** [comment]
Netflix now has AV1 streams, I'm interested in this.

**Comment by CastagnaIT** [comment]
did you get the manifest on the AV1 streams?
can you attach the file here? and specify operative system/machine used?

**Comment by quietvoid** [comment]
I don't know how to get that. I'll look into it.
edit: Anyways I've tried getting an AV1 stream but it's still only serving me HEVC.

**Comment by quietvoid** [comment]
Updating a bit, I just tested the Netflix addon with latest Nexus and IA.  
Selecting AV1 profiles always returns h.264 streams only on my FireTV Stick 4K Max.
