### ISSUE TITLE
Smooth Streaming

### ISSUE THREAD

**Issue by armin884** [xbmc/inputstream.adaptive#274]
Does inputstream.adaptive work when only ism Manifest is available, i have no dash manifest no mp4 file and no PSSH but a widevine license server is present?
```
Format profile              : ISML
Codec ID                    : isml (piff/iso2)
Codec ID/Hint               : IIS Smooth Streaming file format
```
I found this http://docs.unified-streaming.com/documentation/drm/piff2cenc.html . It says you have to create the PSSH box manually
> When a "pssh" box is not present for a DRM system then the Origin synthesizes one just-in-time.
> The "pssh" box for Widevine is synthesized according to the following rules:
> The key_id field is set to the KID as specified in the "tenc" box.
> The provider field is set to 'usp-cenc'.
> The content_id field is copied from the key_id field (in base64).
> The track_type is left empty.
> The policy is left empty.

Is there any script to create PSSH manually?

**Comment by glennguy** [comment]
@armin884 is this still an issue for you? Can we close?
