### ISSUE TITLE
yet another "Could not open / parse mpdURL"

### ISSUE THREAD

**Issue by aleprovencio** [xbmc/inputstream.adaptive#282]
Hello,
I'm getting this error from asciidisco's netflix addon for a long time, since reported on this other issue on that repo: https://github.com/asciidisco/plugin.video.netflix/issues/613

Now I'm using the latest version from the CastagnaIT repo, and still have the same problem, here go the logs: http://ix.io/1MwQ

Maybe you can give me a hint on it?

Thanks

**Comment by CastagnaIT** [comment]
there is another error before inputstream error

TypeError: argument "line2" for method "ok" must be unicode or str

there is some other problem that interrupted the code execution

**Comment by CastagnaIT** [comment]
try to download the latest dayly build,
if there are other problems,
to first open a post "issue" in my netflix github
