### ISSUE TITLE
[question] How to pass license properly?

### ISSUE THREAD

**Issue by Bluescay** [xbmc/inputstream.adaptive#290]
Hi,

My issue is related to #199, I would like to create an addon for the same provider discussed there. However without any success so far.

I could build the mpd URL and I assume it will work fine:

```
AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Type: live, Download speed: 1445065.1648 Bytes/s
```

But I am having issues with the license setting.

It's a widevine stream and I can request the license from this endpoint: `{url}/license/eme` 

However for this to work, I also have to provide a few headers. [Based on the wiki](https://github.com/peak3d/inputstream.adaptive/wiki/Playing-multi-bitrate-stream-from-a-python-addon#description), I tried the following:

```py
license_url = "{url}/license/eme|%s|\b\x04|R{SSM}|" % urllib.urlencode(my_headers)
item.setProperty("inputstream.adaptive.license_key", license_key)
```

(`\b\x04` is the postdata I saw the site is sending always, but not necessary)

But with this method, I get a `ERROR: AddOnLog: InputStream Adaptive: Invalid license_key` always.

Then I tried to get the key myself using the requests library and pass the output binary data directly as the license_key for inputstream (the request returns some bytes always): `ERROR: AddOnLog: InputStream Adaptive: Could not find protocol inside url - invalid`

I got the same cannot find protocol error when I tried to pass the eme endpoint URL only as the license_key and set the stream_headers manually to the urlencoded version of the required headers.

And I got stuck here. How would I do this properly?

Also, I have seen this line in a few addons: `inputstream.adaptive.license_data` what is license_data?

Thanks

**Comment by alannl** [comment]
Did you succeed?

**Comment by alannl** [comment]
license_url = "{url}/license/eme|%s|A{SSM}|" % urllib.urlencode(my_headers)
was the working one, but now it gives error 400.

**Comment by mbebe** [comment]
i have error 400 too. Sometime license invalid, with second token - concurrency - license invalid.

**Comment by mbebe** [comment]
Do you have any solution to get correct license url?

**Comment by sefuns** [comment]
I am also getting 400 for the license request from kodi details mentioned in #279 
Is there a solution for this yet?

**Comment by Sorien** [comment]
@sefuns check licence request headers and payload if they are ok there can be problem with VMP like
https://github.com/peak3d/inputstream.adaptive/issues/199#issuecomment-578535383

if your service supports playback in web browsers you can check if VMP is required by trying to play it in chrome and vivaldi on windows (unlike chrome there but won't be any playback in vivaldi)

**Comment by sefuns** [comment]
Thank you @Sorien, not sure if its related to VMP, problem is Kodi inputstream addon is not able to get to decryption key for video stream.
Because, there are 3 POST requests involved (1st POST with 2 bytes \b\4 and then 2 POSTs most probably related to certificate exchange) in chrome before getting to license key.

But Kodi inputstream addon is not making similar calls, instead there is only one call with 1748 bytes which results in 400 response from server and playback fails with "no keys" error

**Comment by sefuns** [comment]
Yes, as per suggestion I tried setting server certificate still there was no playback so the "mpd" stream is VMP protected so can't be played with Kodi on Linux.

**Comment by matthuo333** [comment]
The HBO Max add-on has just happened to be VMP

**Comment by glennguy** [comment]
@Bluescay can this issue be closed now? It looks like a VMP issue (can't be solved if that's the case)
