### ISSUE TITLE
Cant install old versions from ZIP (Kodi 18.3)

### ISSUE THREAD

**Issue by lenlennart** [xbmc/inputstream.adaptive#294]
Hello,

because of issues with another addon, I want to downgrade my InputStream to version 2.3.13.0.
Upon selecting "Install from ZIP" in Kodi, i get "Failed To Install Addon From Zip File”.
The kodi log says: "ERROR - Cant read [...]/inputstream.adaptive/addon.xml"

Can you help me fix this? 
Alternativly, can you provide me with the extracted addon in version 2.3.13?

Thanks

**Comment by lroeser** [comment]
in fact, i cant install any version from zip.... even the new one (which does work from repo).
