### ISSUE TITLE
Ability to start from first chunk of *.mpd manifest

### ISSUE THREAD

**Issue by bigretromike** [xbmc/inputstream.adaptive#310]
I already posted this on kodi forum, but I would It to also being noticed here.
https://forum.kodi.tv/showthread.php?tid=346141

When I start transcoding file on-a-fly, and I wait until few chunks are created, and then start playing it thru Kodi (inputstream.adaptive), the stream starts around 2 (maybe 3) chunk earlier than the current chunk is being processed, so I'm unable to start from start of the stream.

If I start playing stream while 4th chunk is being processed the chunk that is being played is chunk number 2. I tried `Seek` back but that results in start on chunk of number (current_proccessed_chunk - 2).

manifest looks like this:
```
<SegmentTemplate timescale="24000" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1">
                    <SegmentTimeline>
                        <S t="0" d="258258" r="1" />
                        <S d="381381" />
                        <S d="432432" />
                        <S d="252252" />
                        <S d="288288" />
                        <S d="270270" />
                        <S d="264264" />
                        <S d="282282" />
                        <S d="375375" />
                        <S d="255255" />
                        <S d="279279" />
                        <S d="240240" />
                        <S d="246246" />
                        <S d="484484" />
                        <S d="275275" />
                        <S d="387387" />
                        <S d="240240" />
                        <S d="288288" />
                    </SegmentTimeline>
                </SegmentTemplate>
```

Maybe I'm missing some argument ? maybe there is some setting that I need to set to make this work.

Everything is fine when transcoding is finished and there is no chunk left to processed (which is expected)

Also this is from plugin.video.

**Comment by bigretromike** [comment]
@peak3d hey, any chance to make this work as intention ?
When I start using ffmpeg to transcode video (as VOD), and start playing it while it still doing the encoding I always end up not being able to play video from the start.

I wait for 3rd chunk to be finished by checking if the file is accessible (so there is buffor, and I can measure if transcode machine is quick enough), when that happens I start *.mpd but for some reason it start around 2nd or even 3rd chunk (skipping the beginning of the stream).

Yet, when file finish transcoding it start it without issue from 1st chunk.

As I understand that for live streams starting from most recent chunk is prefer, but for VOD it should start from first (or should be able to give some parameter to start from first)

Usercase: plex/emby/jellyfin alike experience, they work as a VOD-transcoding-streams,  they start encoding video, player start from that point, when user move seekbar they kill the thread and start new with `start time` being the seek point, so each time you load position you start from beginning, then they overwrite GUI so it looks like a normal player :-)

I'm doing something similar but much-much-smaller. Being able to start from 1st chunk from mpd-manifest would be a bless.

**Comment by peak3d** [comment]
Sorry, I have really no idea what you are doing, especially with "transcoding".

**Comment by bigretromike** [comment]
@peak3d, when I start `ffmpeg` with ` -c:v libx264 -f dash -profile:v baseline -level 4 -dash_segment_type mp4 -seg_duration 10 -window_size 720 play.mpd` ffmpeg will start to encoded given video file ( [transcoding](https://en.wikipedia.org/wiki/Transcoding) ).

Now when you wait until `ffmpeg` create 3rd chunk and start playing play.mpd inputstream.adaptive will start playing from the LATEST chunk which will be ~2end or 3rd. But when you play it after ffmpeg finish transcoding/encoding then It will start playing from 1st chunk.

This technic is so called on-fly transcoding.

**Comment by peak3d** [comment]
Maybe ffmpeg sets the type attribute in MPD element to dynamic? Should be set to static for VOD.

<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
(...)
    type="dynamic" <- static for VOD
(...)
>

**Comment by peak3d** [comment]
But yes, I'll add something so you will be able to start from 0 soon

**Comment by bigretromike** [comment]
from shaka-player issue 1832:
`If your MPD may need to be refreshed, you should always mark it as dynamic. This will ensure that the client will refresh when required. A VOD clip can still be dynamic without any issues.`

It would be awesome. Thank you very much !

**Comment by glennguy** [comment]
@bigretromike does the `listitem.setProperty('inputstream.adaptive.play_timeshift_buffer', 'true')` and the .strm equivalent solve this for you? Can we close the issue?

**Comment by bigretromike** [comment]
@glennguy this issue is from 2 years ago, I'm unable to tell if this solved the issue, but will note the solution until I get again to that point in time. Let's close this, and if I get same issue I will reopen my issue, thank you for replaying, its always better that way.
