### ISSUE TITLE
Wrong baseURL

### ISSUE THREAD

**Issue by buruchaga** [xbmc/inputstream.adaptive#315]
mpd file -> 
[ksw-live-test-stream.txt](https://github.com/peak3d/inputstream.adaptive/files/3563488/ksw-live-test-stream.txt)
after play i'm getting 404 error
```
ERROR: AddOnLog: InputStream Adaptive: Download https://n-15-5.dcs.redcdn.pl/livedash/o2/ksw/live/?type=video&ft=1&id=20&bitrate=240000&idx=147245138 failed with error: 404
ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
ERROR: AddOnLog: InputStream Adaptive: Download https://n-15-5.dcs.redcdn.pl/livedash/o2/ksw/live/?type=video&ft=1&id=20&bitrate=240000&idx=147245138 failed with error: 404

```
in mpd:
 ```
<BaseURL>https://n-15-5.dcs.redcdn.pl/livedash/o2/ksw/live/ksw-live-test-stream.livx</BaseURL>
```
so after play - stream address is without **ksw-live-test-stream.livx** before **?type=video&**

Any solution to get correct address?

**Comment by peak3d** [comment]
I'll need the full kodi debug log here, from code / quick test the BaseURL is parsed corectly, maybe it gets replaced later because of redirection?? kodi log will tell us.
