### ISSUE TITLE
Does the inputstream.adaptive use extraordinary manifests? 

### ISSUE THREAD

**Issue by BogdanZawr** [xbmc/inputstream.adaptive#319]
Hello, I have a question to ask and really would appreciate the answer.

I'm using [exoplayer](https://exoplayer.dev/customization.html) on my android app and trying to start DRM MPEG-DASH Widevine video streaming. And had an error of reading manifest(which is processed by your `inputstream.adaptive`). I received this manifest from [plugin.video.netflix](https://github.com/CastagnaIT/plugin.video.netflix) and it is working correctly with this plugin which is starting by Kodi player. Also I use this plugin as a proxy because netflix have MSL(Message Secure Layer), and manifest request returns to player json object which needs to be converted to Mpeg-dash for appropriate manifest in XML format.

Steps which exoPlayer running with netflix manifest before receiving an error:

- InitializePlayer
- buildDrmSessionManagerV18
- Create HttpMediaDrmCallbacks
- Checking the type of manifest (there is the first error, wrong manifest recognizing)
- Generate video\audio\text track object for next track-switching
- MediaPeriodCreated
- Start reading tracks
- Unexpected end of file error
- License request missing.

Example manifes files
[manifestVp-9.txt](https://github.com/peak3d/inputstream.adaptive/files/3583542/manifestVp-9.txt)
[manifest h264.txt](https://github.com/peak3d/inputstream.adaptive/files/3583543/manifest.h264.txt)

Example license
[EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.txt](https://github.com/peak3d/inputstream.adaptive/files/3583557/EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.txt)

 files

**Comment by peak3d** [comment]
Sorry, I'm not using / developing on exoplayer, you'll have to debug what elements / attributes lead to the issue.
