### ISSUE TITLE
How would I go about setting inputstream.adaptive to be eneabled by default?

### ISSUE THREAD

**Issue by jrtz4** [xbmc/inputstream.adaptive#323]
As the title states, I have a custom kodi android apk, and I'm wondering if someone could direct me in the right direction into changing the code so it would be enabled by default?

**Comment by peak3d** [comment]
This is a kodi change. From concept it should be enabled automatically from the time an addon has listed inputstream.adaptive as dependency. But - its more an issue for the kodi github issue section.

**Comment by dagwieers** [comment]
@peak3d Should we keep this issue open to track Kodi (has this been reported upstream?), or do you prefer to close this instead?

**Comment by peak3d** [comment]
Yes, open is fine, still a todo

**Comment by glennguy** [comment]
@dagwieers isn't this handled by inputstreamhelper?

**Comment by dagwieers** [comment]
@glennguy Yes, inputstreamhelper enables ISA if it isdisabled (for whatever reason). However, it cannot take care of installing ISA if it is not part of the Kodi distribution (i.e. an extra package).
