### ISSUE TITLE
Video/Audio freeze on second Period on Raspberry Pi

### ISSUE THREAD

**Issue by dagwieers** [xbmc/inputstream.adaptive#332]
I am reporting this here because [this was reported by several people](https://github.com/michaelarnauts/plugin.video.vtm.go/issues/1#issuecomment-536335806) now using the VTM GO add-on ons Raspberry Pi. This is based on [a custom ARM build of the master branch from Sep 27](https://github.com/michaelarnauts/plugin.video.vtm.go/issues/1#issuecomment-536220725).

- When playing any VTM GO stream using multiple periods, the first period seems to play correctly (this is the opening commercial) then when the second period is starting the video stalls after only a few seconds, audio continues, everything stops (may go black) and playback fails.

- If during the video/audio stall in that second period the stream is being paused (often twice) the stream does seem to pick up and play correctly.

There is some confusion to what the policy is for the different branches (Leia, Matrix and master).
- The Matrix branch has some fixes (e.g. for subtitles) that we would like to see for Leia as well. What is the plan here? Is everything being backported to Leia (but with delay) or is there an effective fork?
- Is the master branch supposed to work correctly on Leia currently?

In the below included log Kodi did continue playing the stream after about 20 seconds of video/audio stalling. In other cases it would bail out.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3676265/kodi.log)

**Comment by dagwieers** [comment]
cc @peno64 @mediaminister @michaelarnauts

**Comment by dagwieers** [comment]
I also have to add that this build of the master branch causes subtitles to fail. I no longer see any subtitles in VRT NU and VTM GO.

**Comment by peno64** [comment]
@dagwieers 
I don't have those problems with the subtiles. They work normally with this compiled version of me.
Both in vrt.nu and vtm go I do have them.
Are you sure that you checked the setting to show subtitles when available?

**Comment by peno64** [comment]
But the original reported problem I do also have on both pi3 & pi4

**Comment by dagwieers** [comment]
Related to the subtitles, it is possible that was a specific issue with VRT NU (for VTM GO it is likely there was no subtitle in the manifest). Last night subtitles did work in VRT NU. (BTW on Netflix subtitles always worked)

**Comment by michaelarnauts** [comment]
I've successfully build the master branch for Leia, so I guess that the current master branch can be merged into Leia. This would fix a lot of hassle for getting the latest Period fixes to work on Kodi 18.

Is there anything that is preventing this release for Leia?

**Comment by mediaminister** [comment]
Last thing I heard was that there are changes needed to Kodi videoplayer core to make short Periods play 100% smoothly. A pull request was first merged and reverted afterwards: https://github.com/xbmc/xbmc/pull/16706

I doubt there will be a "Periods" release for Kodi Leia because of this.

**Comment by glennguy** [comment]
@dagwieers is this issue still current?

**Comment by dagwieers** [comment]
Not sure with the recent fixes for Matrix. I only have Leia devices so I cannot test them.

**Comment by CastagnaIT** [comment]
since Leia build is discontinued and no fixes will be backported i close this Issue,
if there are problems on Matrix or Nexus please open a new issue
