### ISSUE TITLE
Will not install on Android based Kodi 18.4

### ISSUE THREAD

**Issue by Condottiero1** [xbmc/inputstream.adaptive#333]
It works perfectly on Windows, but no way to install it on Android box. It does not show in the Kodi repo and will not install from the zip file. Thanks

**Comment by M2k80** [comment]
kodi 18.4 has inputstream adaptive included, no need to install. go to the installed plugins and simple activate it

**Comment by cab19** [comment]
Won't install for me, checked installed plugins, not there (input stream helper is), but some content is still demanding inputstream adaptive. Tried via kodi repo, tried installing latest zip. Everything fails.

**Comment by ThePapaw** [comment]
Yeah, I have been trying to find a way to add it to a shield for a while now. I can sling.tv addon needs it. Any help would be appreciatted

**Comment by ThePapaw** [comment]
For those using shields, I think I have discovered why this is only happening to some of us. It appears to be a 32/64 bit issue. I backed up my data and uninstalled the arm64bit version, installed armeabi-v7a (32bit) version and there it was. I have tried this with v18.1,18.2, and 18.3. I have no idea why it isn't available in the arm64 version

**Comment by Dorme** [comment]
Same here; inputstream adaptive is not shown in the installed addon list (only input stream helper).

**Comment by LendoK** [comment]
Same here, with Kodi 18.4 on Raspbian

**Comment by dagwieers** [comment]
IIRC on Raspian **inputstream.adaptive** is in a separate Debian package named **kodi-inputstream-adaptive**. You have to install this yourself.

**Comment by LendoK** [comment]
> IIRC on Raspian **inputstream.adaptive** is in a separate Debian package named **kodi-inputstream-adaptive**. You have to install this yourself.

Worked for me. Thanks!
