### ISSUE TITLE
DASH load audio before video?

### ISSUE THREAD

**Issue by shycoderX** [xbmc/inputstream.adaptive#347]
Is it possible to load the audio before the video loads? I am asking because in my plugin when a stream is selected the video plays and after 5 seconds or so the audio kicks in too.

It would be nice if both were in sync. I don't know if there is already an option for that?

**Comment by dagwieers** [comment]
I think this is related to PR #133

**Comment by glennguy** [comment]
@shycoderX is this now fixed since then? Can we close the issue?
