### ISSUE TITLE
No sound on HLS

### ISSUE THREAD

**Issue by seth--** [xbmc/inputstream.adaptive#354]
I'm playing the following stream but don't get audio: http://186.0.233.76:1935/Garage/smil:garage.smil/playlist.m3u8

Audio settings -> audio stream shows "[Unknown] - AAC  - 0 channels (1/1)"

I tried both auto and manual stream selection

The same link works perfectly on vlc on my computer (kodi is running on  a rpi). Playing it on kodi without inputstream.adaptive results in a laggy video with sound

Log:

> 
> 2019-11-22 00:16:06.174 T:1902216032  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.elgaragetv/?action=play
> 2019-11-22 00:16:06.211 T:1574933216  NOTICE: Creating InputStream
> 2019-11-22 00:16:06.277 T:1574933216  NOTICE: Creating Demuxer
> 2019-11-22 00:16:06.278 T:1574933216  NOTICE: Opening stream: 1 source: 256
> 2019-11-22 00:16:06.425 T:1574933216  NOTICE: Creating video codec with codec id: 27
> 2019-11-22 00:16:06.439 T:1574933216  NOTICE: Creating video thread
> 2019-11-22 00:16:06.441 T:1574933216  NOTICE: Opening stream: 4 source: 256
> 2019-11-22 00:16:06.442 T:1574933216  NOTICE: Finding audio codec for: 86018
> 2019-11-22 00:16:06.443 T:1574933216  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
> 2019-11-22 00:16:06.443 T:1574933216  NOTICE: Creating audio thread
> 2019-11-22 00:16:06.444 T:1422353120  NOTICE: running thread: CVideoPlayerAudio::Process()
> 2019-11-22 00:16:06.450 T:1370485472  NOTICE: running thread: video_thread
> 2019-11-22 00:16:07.047 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:13.155 T:1422353120 WARNING: Previous line repeats 5 times.
> 2019-11-22 00:16:13.155 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:17.197 T:1370485472  NOTICE: Previous line repeats 1 times.
> 2019-11-22 00:16:17.197 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:21.832 T:1422353120 WARNING: Previous line repeats 3 times.
> 2019-11-22 00:16:21.832 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:23.464 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:35.996 T:1422353120 WARNING: Previous line repeats 18 times.
> 2019-11-22 00:16:35.996 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:36.040 T:1422353120  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
> 2019-11-22 00:16:36.042 T:1422353120  NOTICE: Previous line repeats 1 times.
> 2019-11-22 00:16:36.042 T:1422353120  NOTICE: Creating audio stream (codec id: 86018, channels: 1, sample rate: 7350, no pass-through)
> 2019-11-22 00:16:36.614 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:46.402 T:1422353120 WARNING: Previous line repeats 12 times.
> 2019-11-22 00:16:46.402 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:47.214 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:50.541 T:1422353120 WARNING: Previous line repeats 6 times.
> 2019-11-22 00:16:50.541 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:53.114 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:57.719 T:1422353120 WARNING: Previous line repeats 3 times.
> 2019-11-22 00:16:57.719 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:58.497 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:16:58.756 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:16:59.580 T:1370485472 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2019-11-22 00:17:02.914 T:1422353120 WARNING: Previous line repeats 6 times.
> 2019-11-22 00:17:02.915 T:1422353120  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 2019-11-22 00:17:42.001 T:1873797856 WARNING: ActiveAE - large audio sync error: -42480.688624
> 2019-11-22 00:17:42.002 T:1873797856 WARNING: ActiveAE - large audio sync error: -42486.313572
> 2019-11-22 00:17:47.004 T:1873797856 WARNING: ActiveAE - large audio sync error: -47376.257320
> 2019-11-22 00:17:47.005 T:1873797856 WARNING: ActiveAE - large audio sync error: -47331.262736
> 2019-11-22 00:17:47.009 T:1873797856 WARNING: ActiveAE - large audio sync error: -47287.256746
> 2019-11-22 00:18:04.361 T:1873797856 WARNING: ActiveAE - large audio sync error: 9903.840187
> 2019-11-22 00:18:04.362 T:1873797856 WARNING: ActiveAE - large audio sync error: 9947.840709
> 2019-11-22 00:18:04.364 T:1873797856 WARNING: ActiveAE - large audio sync error: 9993.840396
> 

main.py:

```
# -*- coding: utf-8 -*-
import sys
from urllib import urlencode
from urlparse import parse_qsl
import xbmcgui
import xbmcplugin

_url = sys.argv[0]
_handle = int(sys.argv[1])
xbmc.log("HANDLE "+str(_handle), xbmc.LOGWARNING)

VIDEO="http://186.0.233.76:1935/Garage/smil:garage.smil/playlist.m3u8"


def get_url(**kwargs):
    xbmc.log("get url", xbmc.LOGWARNING)
    xbmc.log('{0}?{1}'.format(_url, urlencode(kwargs)), xbmc.LOGWARNING)
    return '{0}?{1}'.format(_url, urlencode(kwargs))


def list_categories():
    xbmc.log("list categories", xbmc.LOGWARNING)
    xbmcplugin.setPluginCategory(_handle, 'El Garage TV')
    xbmcplugin.setContent(_handle, 'videos')
    list_item = xbmcgui.ListItem(label="El Garage TV")
    list_item.setArt({'thumb': "https://cdn.mitvstatic.com/channels/ar_el-garage_m.png",
                      'icon': "https://cdn.mitvstatic.com/channels/ar_el-garage_m.png",
                      'fanart': "https://cdn.mitvstatic.com/channels/ar_el-garage_m.png"})
    list_item.setInfo('video', {'title': "El Garage TV",
                                'genre': "Motorsports",
                                'mediatype': 'video'})
    list_item.setProperty('IsPlayable', 'true')
    url = get_url(action='play')
    is_folder = False
    xbmcplugin.addDirectoryItem(_handle, url, list_item, is_folder)
    xbmcplugin.addSortMethod(_handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
    xbmcplugin.endOfDirectory(_handle)


def play_video():
    xbmc.log("play video", xbmc.LOGWARNING)
    play_item = xbmcgui.ListItem(path=VIDEO)
    play_item.setProperty('inputstreamaddon', 'inputstream.adaptive')
    play_item.setProperty('inputstream.adaptive.manifest_type', 'hls')
#    play_item.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')
    xbmcplugin.setResolvedUrl(_handle, True, listitem=play_item)


def router(paramstring):
    xbmc.log("router", xbmc.LOGWARNING)
    params = dict(parse_qsl(paramstring))
    if params:
        if params['action'] == 'play':
           play_video()
        else:
            raise ValueError('Invalid paramstring: {0}!'.format(paramstring))
    else:
        list_categories()


if __name__ == '__main__':
    xbmc.log("MAIN", xbmc.LOGWARNING)
    router(sys.argv[2][1:])
```

**Comment by L2501** [comment]
it uses MP3 audio, that is not implemented by the plugin.
https://github.com/peak3d/inputstream.adaptive/blob/7ad714da627fe0c0740b4c0970e27faa20039bbc/src/parser/HLSTree.cpp#L71

**Comment by glennguy** [comment]
Even if mp3 were to be implemented, the playlist provided has no `CODECS` attribute in the `EXT-X-STREAM-INF` tag so with the default presumably still being aac the audio would not play.

Fwiw I tested the stream with mp3 hardcoded, and the video/audio was still laggy.
