### ISSUE TITLE
Multirights DRM

### ISSUE THREAD

**Issue by cimbor** [xbmc/inputstream.adaptive#356]
Hi, i have a subscription to the Mexican service service izzi go, and i have discovered recently that they use fullhd mpd streams thought web navigators with proper support. I have used dev tools in chrome to inspect how they use them:

[https://ott-live-izzigo.akamaized.net/live1-dash/HD-Fox-Sports-2/default.mpd](url)

They include a default_KID value and various content schemeiduri

{"responseCode":"OPERATION_SUCCESSFUL","err":0,"mes":"OK","ver":0,"allowed":true,"provider":"elemental","videos":[{"url":"https://ott-live-izzigo.akamaized.net/live1-dash/HD-Warner/default.mpd","format":"MULTIRIGHTS","packg":"DASH","licenses":[{"url":"https://gowv.teleparallevar.tv:8063?deviceId=NDM5MjQ5NjMtMWM2OS0zMGE3LTk5MGYtMTY4NWZiNmQ2OTc2","system":"com.widevine.alpha","drm":"WV","drm-provider":"verimatrix"}]}]}

Unlike other DRM encripted streams like Clarovideo, the post request to the license server includes a Request Payload instead of a Widevine Body.

Is it possible to play this streams on kodi?

**Comment by Sicario66** [comment]
Hi,cimbor
when you opened your dev tools did you see the license? what is it? that might help ...
on the other hand did you try to open the link in kodi while being connected on izzygo because what you describe could just be a double authentication as it exists on other sites and would require to code in this direction

**Comment by horaxio** [comment]
Hi Cimbor °!°!°!
ya te la pelatexxx°!°!!
please m3u8!!!

**Comment by glennguy** [comment]
@cimbor is this issue still current?

**Comment by locotv1993** [comment]
Hola escríbeme te puedo ayudar a sacarlos y también a que funcionen

**Comment by Leohalliwell** [comment]
> Hola escríbeme te puedo ayudar a sacarlos y también a que funcionen

¡Hola Loco! ¿Sabes hacerlo tambien con los t0t4l pl4y? Es que es el unico que tiene el canal azteca un0 -2hrs :(

**Comment by locotv1993** [comment]
I can try, friend, I just need access to the accounts, write me on telegram
@Max_t0

**Comment by locotv1993** [comment]
Azteca uno 

https://stream.ads.ottera.tv/playlist.m3u8?network_id=4833

**Comment by enpizo** [comment]
Que tal loco, tengo el mismo requerimiento, obtener los canales de IZZI GO con un panel DRM, se puede desbloquear y que funcionen bien?
