### ISSUE TITLE
How to get Matrix version on LibreELEC armhf?

### ISSUE THREAD

**Issue by XxAcielxX** [xbmc/inputstream.adaptive#360]
Hello,

I'm using a SBC based on RK3399, using the nightly kodi v19 and I'm unable to get the latest version of the Add-on in the Repo.

How am I suppose to update to the latest version? Some help will be appreciated. 

Thanks & regards

**Comment by dagwieers** [comment]
It would indeed be nice to have build infrastructure for ARM devices. Maybe LibreELEC or OSMC could help here?

**Comment by chalbersma** [comment]
I'm not with either, but what would be needed to build for arm and include with the default kodi plugins?

**Comment by glennguy** [comment]
We don't supply builds in the official repo for linux platforms, you would have to check your package manager. LibreELEC/CoreELEC have their own repos, there's the Ubuntu PPA etc.
