### ISSUE TITLE
DASH / MPD  /  WIDEVINE  / error  404

### ISSUE THREAD

**Issue by zbyna** [xbmc/inputstream.adaptive#362]
Hi,
I am trying to implement dash support in an addon.
There are two types of videos in the site I intend to play in Kodi:
 1st  - with a requirement of widevine license and 
2nd - which does not need a license to play  - no communication with the license server spotted

Everything below touches 2nd type:
Kodi is able to reach mpd file: 
```T:1240 DEBUG: CCurlFile::Open - effective URL: <http://ivys-vst09-6.o2tv.cz/atip/2e983a383516c8af5e7249283d550860/1576186151328/61924494877667998-720p.mpd>
T:1240 DEBUG: AddOnLog: InputStream Adaptive: Effective URL http://ivys-vst09-6.o2tv.cz/atip/2e983a383516c8af5e7249283d550860/1576186151328/61924494877667998-720p.mpd
T:1240 DEBUG: AddOnLog: InputStream Adaptive: Download http://ivys-cdn.o2tv.cz/cdn/uri/get/?token=b687684f4600b92c5d1e23986cf0e66ae5371d90&contentType=vod&drmOnly=false&expiry=1576189750&id=61924494877667998&playerType=dash&quality=720p&region=1&skipIpAddressCheck=true&userId=fa78bc57-f9d2-4d97-bbc2-b143fc69621d&encryption=wv finished
T:1240 INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Type: VOD, Download speed: 2391157.9192 Bytes/s 
```
but attempt to download  mp4 is not successfull:
```
T:1240   ERROR: AddOnLog: InputStream Adaptive: Download http://ivys-vst09-6.o2tv.cz/atip/2e983a383516c8af5e7249283d550860/1576186151328/1101-1505/IS.mp4 failed with error: 404
```
It is possible to play the mpd file with [ this chromium addon ]( https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn )
At Kodi addon I added every possible header which browser used, only difference between browser and Kodi  from my point of view is this operation:
```
 curl -k -i --raw -o 24.dat "https://ivys-vst11-6.o2tv.cz/get-utc-timestamp"  ...
```
Here is mpd file:  [61924494877667998-720p.zip](https://github.com/peak3d/inputstream.adaptive/files/3958072/61924494877667998-720p.zip)
 kodi log for 1 thread: [Filter Results.zip](https://github.com/peak3d/inputstream.adaptive/files/3958107/Filter.Results.zip)
whole kodi log: [kodi.zip](https://github.com/peak3d/inputstream.adaptive/files/3958108/kodi.zip)

Thank you for any clarification.  Widevine is big new for me so it is possible I am missing some obvious points.

EDIT:
Seems like 
```
<BaseURL>http://ivys-vst09-6.o2tv.cz/aa/f33a8c2d6f63e52efef945c1a4125697/1576186151328/a5464e14cd07387e534ed1d273d5ff4f9/dna-61924494877667998-720p/</BaseURL>
```
is not used for  constructing the path to  IS.mp4 and instead of it  the path to mpd : 
```
http://ivys-vst09-6.o2tv.cz/atip/2e983a383516c8af5e7249283d550860/1576186151328/
```
is used.

**Comment by wombat01** [comment]
Same issue.

**Comment by glennguy** [comment]
@zbyna @wolfgar is this issue still current?
