### ISSUE TITLE
Limit on subtitle tracks?

### ISSUE THREAD

**Issue by rgainza** [xbmc/inputstream.adaptive#365]
Is there a limit to the number of subtitle tracks there can be in a dash manifest for inputstream? I managed to load 20 subtitles. The annoying part was that the subtitles that wasn't loaded was the one that I searched for.

This happens in ARM and PC so I'm guessing all units are affected by this if they ever got that many subtitles available.

**Comment by rgainza** [comment]
After experimenting with it more I noticed that it has nothing to do with the number of subtitle tracks. Inputstream has a limit on a total of 32 tracks or rather "AdaptationSet" which can be video, audio and subtitles. 

Is this done on purpose or might it be a limit from Kodi?

**Comment by CastagnaIT** [comment]
Picked from a old discussion:
> It's this one which limits the amount of streams which can be xchanged between kodi and inputstream basted addons: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h#L98

**Comment by rgainza** [comment]
> Picked from a old discussion:
> 
> > It's this one which limits the amount of streams which can be xchanged between kodi and inputstream basted addons: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h#L98

Look at that! I have to go through code more often but I'm not good at C++...

Is there a special reason for this? Or can I expect inputstream to be compatible if I change that line?

**Comment by CastagnaIT** [comment]
I honestly can't remember why there is this limit, you should ask to Kodi Team
lately Peak3d has little time to follow here

**Comment by glennguy** [comment]
Fixed in Matrix
