### ISSUE TITLE
Inputstream adaptive crashing kodi 18.5

### ISSUE THREAD

**Issue by chamchenko** [xbmc/inputstream.adaptive#368]
I'm having an issue with this kind of manifest.
[Manifest](https://pastebin.com/raw/SF8CTKeD)
[LOG](https://pastebin.com/raw/TaNxiMZV)
After loading manifest kodi hangs for few seconds before crashing, I'm using the 2.4.2 version on kodi 18.5. I have also tried with kodi 19 alpha release and 2.5.3 wish resulted in the same behaviour.

**Comment by dagwieers** [comment]
Maybe you could try the upcoming v2.4.3 to see if this fixes your issue. See #387

**Comment by glennguy** [comment]
@chamchenko closing this (old and log has expired), let us know if it's still an issue

**Comment by chamchenko** [comment]
Yes no problem it's has been a while, I haven't really got around to update this add-on.
