### ISSUE TITLE
inputstream.adaptive not starting correctly on LibreELEC 9.2 x64

### ISSUE THREAD

**Issue by NeverEatYellowSwissSnow** [xbmc/inputstream.adaptive#369]
I am using LE 9.2 Generic x64 with the Teleboy PVR Client Addon which has some dependencies on inputstream.adaptive Addon.

Now the problem is that inputstream.adaptive is not starting as it should.

To get the Teleboy PVR Client to work I have to do the following steps everytime I reboot LE:

- Disable Teleboy PVR Client addon

- Disable inputstream.adaptive addon 

- Enable inputstream.adaptive addon

- Enable Teleboy PVR client addon

Any fix would be appreciated.

**Comment by hoksilato2** [comment]
I use LE 9.2 on rasppi 4 and netflix and amazon vod addon has problem with adaptive too. It seems some problem with refresh or screen resolution. Other stream services or local video works perfectly.
