### ISSUE TITLE
max./min. bandwidth setting, and expected behaviour of the addon.

### ISSUE THREAD

**Issue by T-C-R** [xbmc/inputstream.adaptive#385]
I´m not sure what is the intended behaviour of the min./max. bandwidth option in the config of the addon: I got that there is no implementation of adaptive bandwidth switching yet. But what does the max. bandwidth value do in that regard ? The min. bandwidth should preselect the stream, but it the same with max. bandwidth ?

Reason of my question is that, obviously, my ISP have a weak peering with Netflix which translates into a shortage of bandwidth at evening times (only). 
I found that out as I did some tests with a customised firefox browser (with the 1080p addon): At evening times also there the bandwidth has some weak moments. But as this client will adapt to a change in bitrate by reducing resolution, and Inputstream.adaptive does not, there is no buffer observed in the browser. However, in Kodi, the result is a stall because vq and aq are getting empty ... and the Inputstream.adaptive is sticking to the stream that was selected by start.
I´ve done some tests now with the min/max bandwidth in this addon setting to give range to the Netflix addon that it can deal with. Actually I have 3Mbit/s for Min. + 6MBit/s for Max applied, and the Netflix addon max. res. reduced to 720p. This seems to work and no stall is being caused.
BUT: The bandwidth of the stream, however, is not quite sticking to this range... I have streams that are between 380k and 2.6Mbit, causing a network utilisation of up to 10Mbit/s in peaks.

So neither the video bitrate nor the network utilisation is within the selected range. Has this been tested by releasing the addon, or should I do some thorough testing on it ?

**Comment by glennguy** [comment]
The stream selection can only go off of what is give to inputstream.adaptive in the manifest. The bitrate in the manifest is sometimes a maximum bitrate, sometimes an average. Once the stream has started the decision has been made. Until adaptive bitrate switching is implemented we can't suggest much but to lower the quality.
One thing you could try for now is to set the stream selection to 'manual' in inputstream.adaptive settings and use the OSD to change bitrates when it's needed. But this will affect all add-ons using IA.

@T-C-R is this issue ok to close now?

**Comment by T-C-R** [comment]
@glennguy 
well this response and advice is coming back to me too late now... I opened it 15 months ago and got no reaction.
I meanwhile stopped the Kodi project completely and bought myself an Amazon stick with the genuine Netflix client. 
This client is able to cope with bandwidth adaptation, but at the end I also believe that to run all this in a QNAP HD-Station is simply too much for this platform. The firestick is doiong way better, also because it supports HW-acceleration even with Netflix (as certified device).
Anyway, thanks for your response, you can consider it closed as I don use it any longer.
