### ISSUE TITLE
VOD video problems - Missing support for Kodi stream buffering

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/inputstream.adaptive#392]
Since always, and especially in recent months many users complain about problems in the playback

These problems are due to latencies in the VOD service or networks that are not always stable due to the ISP or WIFI.

The problem is the lack of a buffer,
getting the data in real time is not a good way to VOD playback

I do not know if it is already supported, in this case closed the Issue, i just need to know how to customize it and increase the size.

Myself have buffering problems and it starts to get worse:
- at best, playback pauses and resumes after about 10/15 seconds
- at worst, the playback is stopped and exit to the list screen, and you have to resume it

This can also happen several times in a single playback

It would be a good idea to use Kodi buffer to load as much data as possible in as little time as possible, in order to suppress these problems

**Comment by glennguy** [comment]
This has come up a few times before, see #8 and #14 for example.

It would be great to have but it's not trivial to implement. At the moment from what I can see segments are only downloaded at Kodi's request (to fill 8 second internal buffer - cannot be changed) so there would need to be a whole new section built to have our own buffer within inputstream adaptive, associated logic, also buffering for different streams (for adaptive bitrate switching)... I'm sure more things!

If waiting for this isn't an option you could do a proxy server in python to pre-download future segments

**Comment by zero972** [comment]
I came across this issue also, 8 sek. internal buffer is propably to small for flawless playback, especially with 4k content. Adaptive bitrate switching is nice to have, but not a deal breaker since you can switch the streams by yourself if needed. 

Maybe adding a buffer for the actual stream first (to fix the playback issues) would be a lot less work to do as to implement both features at once?

**Comment by yoshimo** [comment]
How does this compare to https://kodi.wiki/view/HOW-TO:Modify_the_video_cache `?
That page describes how to increase the cache for 

> all video files, including local network, internet, and even the local hard drive. Default value is 0 and will only cache videos that use internet file paths/sources.

**Comment by dagwieers** [comment]
I have asked for better triage in this project so we can make open feature requests more upfront, rather than having the same thing being brought up ever so often in another issue. It doesn't help to converge to a proper fix (or get the proper attention from those that can implement it).

**Comment by dagwieers** [comment]
We can already use the Wiki to document and track features or known issues, so don't let that keep us from collaborating ;-)

**Comment by Besur** [comment]
are you guys talking about artefacts with DRM vod playback like this https://imgur.com/8fuO9Px ? cause i don't know if i have to open an issuer for my problem

**Comment by CastagnaIT** [comment]
no we are just talking about buffer management here

**Comment by CastagnaIT** [comment]
someone know the code line where is set the 8 second of internal buffer?

**Comment by glennguy** [comment]
I had a quick look on github but could not find it, it might be easier using an IDE to trace it back. Kodi calls DemuxRead() in inputstream.adaptive to get more data, you could start there...

**Comment by dagwieers** [comment]
@CastagnaIT @peak3d already offered this as a solution for another issue (see https://github.com/xbmc/xbmc/issues/16003#issuecomment-494578740) and this was what he proposed: https://github.com/peak3d/xbmc/commit/9b633ec87be189edb4413a5a60aeebf7868e228c

**Comment by yoshimo** [comment]
A simple static increase feels wrong, what if a person wants to watch high res, and take  a few minute buffering into account for something the internet connection usually can't do "live"?

**Comment by dagwieers** [comment]
@yoshimo Read the discussion by following the link. No need to repeat the same discussion here.

**Comment by CastagnaIT** [comment]
thanks for the links

**Comment by dagwieers** [comment]
@CastagnaIT Keep us posted about your findings, as I am sure you will :wink:

**Comment by michaelarnauts** [comment]
I just looked a bit into this issue, and the 8 second limit is the reason for all sorts of problems.

-> https://github.com/add-ons/plugin.video.viervijfzes/issues/4
-> https://github.com/add-ons/plugin.video.vtm.go/issues/139

Altough this issue is not in inputstream, but in Kodi itself.

**Comment by afxx777** [comment]
i raised the video player internal buffers to 12 sec and recompiled it for android (Shield Pro 2019). Rasing the internal buffer doesnt fix this isse, i still have random duplicate / dropped frames when playing 4k content from Netflix.

**Comment by matthuo333** [comment]
Was this no result in the end?

**Comment by glennguy** [comment]
The work is in #506 however it needs some adjustments before it can be brought in. Likely to be a Kodi 20 feature

**Comment by matthuo333** [comment]
> The work is in #506 however it needs some adjustments before it can be brought in. Likely to be a Kodi 20 feature


So I need to add the 7 files in #506 to the project to compile? How does it fit into the current version?

**Comment by glennguy** [comment]
Fixed in #732

**Comment by Vikassm73** [comment]
Does local buffering is really implemented in Inputstream

Without Inputstrem
![ffmpeg](https://github.com/xbmc/inputstream.adaptive/assets/41675437/fa9fcae8-a7a0-495d-ab0b-005c2f1cc5b3)


With Inputstream
![Inputstream](https://github.com/xbmc/inputstream.adaptive/assets/41675437/d3027ace-2f75-495f-a87d-b3959cc6559d)
