### ISSUE TITLE
Max Resolution Not Being Reached

### ISSUE THREAD

**Issue by eracknaphobia** [xbmc/inputstream.adaptive#49]
When setting stream selection to manual, I can stream the url below at the highest setting (720 @ 60fs) without a hitch. However when I leave it on auto it doesn't go past the 640x360 stream? I've tried a couple different settings but nothing seems to allow the adaptive stream move up in stream quality.

- Kodi 18 Win x64 compiled Aug 9th 2017 
- inputstream.adaptive 2.0.7

http://md-akc.med.nhl.com/hls/nhl/2017/01/07/7f10fce3-9fea-4b14-8e62-65e4f4082991/1483823984448/master_tablet60.m3u8

**Comment by glennguy** [comment]
@eracknaphobia are you running in a window by any chance? inputstream.adaptive factors in the screen (window) resolution when deciding on a stream. That one cost me a couple of hours of head scratching!

**Comment by eracknaphobia** [comment]
Bingo! Thanks for the quick response.

**Comment by eracknaphobia** [comment]
I suppose I should leave this issue you open, since you brought up another issue with resolution after resize.

**Comment by peak3d** [comment]
Yes, can be left open until stream switching is implemented.

**Comment by hawkeyexp** [comment]
Hi, will add here, cause i have also a resolution problem with netflix plugin.
When max res secure is set to 480p cause rpi3 has sometimes performance probs with 720p stream results in 512x384. While playing with bandwidth settings it is possible to get 720x480p.
With the amazon plugin for example i could release 1280x528p which is totally smooth in playback.
Is it possible to add a predefined res between 480p and 720p? Possible 576 or 640 ?

**Comment by peak3d** [comment]
@hawkeyexp yes, sure, will do next time Im at this code place

**Comment by CastagnaIT** [comment]
Issue closed since now in Kodi 20 has been handled resolution change in windowed mode
