### ISSUE TITLE
Adobe HDS Support

### ISSUE THREAD

**Issue by yoshimo** [xbmc/inputstream.adaptive#80]
Some Websites still prefer Adobe HDS for their streams as described in https://www.encoding.com/http-dynamic-streaming-hds/, preferrably even with Flash as a Wrapper.

Some of the streams can be dumped via  KSVs php script https://github.com/K-S-V/Scripts to flv files, converted and then be played in Kodi.

It would be nice if we could skip this and play the streams directly in Kodi.

**Comment by glennguy** [comment]
@yoshimo for what it's worth the f4mproxy script can currently play HDS streams directly in Kodi.

**Comment by peak3d** [comment]
@yoshimo its on my todo list.

**Comment by peak3d** [comment]
From what I read is HDS nothing wich changes the world in future.
Until this argument is not discussed away, I would agree to @glennguy and use the proxy.

If I'm wrong, pls. let me know....

**Comment by Gujal00** [comment]
@peak3d 
Please consider supporting HDS in Inpustream adaptive.
Though f4mproxy plays HDS well, every single repo that hosts it, is in the Kodi Banned repo list.
It would be nice to have Inputstream adaptive play HDS, HLS and ISM, a one stop shop for all the three major adaptive streaming formats.
Thanks
