### ISSUE TITLE
stream selection manual -> lowest resolution automatically played

### ISSUE THREAD

**Issue by dav-sap** [xbmc/inputstream.adaptive#90]
Is there anything that needs to be added to the addon for the selection manual to work?
When I use it now I get the lowest resolution played. When it's auto i get a higher resolution.
The usage in the addon is:
```
            playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
            playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
            playitem.setProperty('inputstream.adaptive.stream_headers', url.split('|')[1])
            playitem.setProperty('inputstream.adaptive.license_key', '|' + url.split('|')[1])
            playitem.setProperty('IsPlayable', 'true')
```

**Comment by JinRonin** [comment]
With manual stream selection you can change the resolution while the stream is playing.

**Comment by dav-sap** [comment]
Where do i change the resoution? I tried, couldn't find the option

**Comment by JinRonin** [comment]
OSD Settings (right corner) Video Settings

**Comment by peak3d** [comment]
Next rework will remove auto / manua options.
It will behave as manual but with the correct stream preselected.

**Comment by dav-sap** [comment]
I don't think the license key is being set when I switch the resolution, cause when I try to switch I get the 403 Forbidden error, any idea?
