### ISSUE TITLE
Start Live Stream (sliding window) from Begining

### ISSUE THREAD

**Issue by eracknaphobia** [xbmc/inputstream.adaptive#94]
Something that has been requested for almost all sports addons is the ability to start a live, in-progress game from the beginning. Is there a possibility that inputstream.adaptive would be able to take in such a setting in order to start a live stream at a time in the past?

Similar Request:
https://github.com/aqw/xbmc-gamepass/issues/278

Possibly Relevant Here:
https://github.com/chrippa/livestreamer/issues/1230

**Comment by peak3d** [comment]
Have you tried to set this otion in listItem (playFrom 0)?

**Comment by eracknaphobia** [comment]
I will now, never knew this was an option. My second question is what units is this in seconds, milliseconds, something else? I ask because, at least with hockey games, there is about 1.5 to 2 hours of "The game will begin shortly", so I would need to set it to something greater than zero.

**Comment by eracknaphobia** [comment]
Sorry, I'm still a bit confused. First you reference the parameter as playFrom, then you call it startat? Do you have an example of how to use this?

**Comment by peak3d** [comment]
Sorry, I'm not a python dev, I only know that it is possible to set in any way.
Have it seen some time ago, but no clue what the exact name is / was.

**Comment by JinRonin** [comment]
I would also like to have something to start streams at a certain point.
I've used to use setProperty('startPercent') but without success now.

**Comment by eracknaphobia** [comment]
@rbuehlma awesome! So is this only for PVR addons or can I leverage it in my video addons?

**Comment by rbuehlma** [comment]
This PR was only for PVR addons but as far as I know, Python addons can already now control the player in such a way, but I'm not sure about this.

**Comment by bigretromike** [comment]
I'm also interested in this.
I tried to start player `xbmc.Player().play(url_to_strm, startpos=0)` without success.
Also when Im using player "chapter back" it start from same place which started playing, aka current latest chunk (from my observation). Then after some time I can't even go back to those chunks, and Im not deleting the content also.

Any chance to force it with header in strm file or how to control it ?

Or maybe there is special argument to pass to ffmpeg to force this mode?

**Comment by bigretromike** [comment]
> 
> 
> This PR was only for PVR addons but as far as I know, Python addons can already now control the player in such a way, but I'm not sure about this.

I would like to know how to does that in video addon, @rbuehlma @eracknaphobia

**Comment by eracknaphobia** [comment]
Here's how I handle it in the NHL addon. It's a hack for sure. Basically I start the stream then wait for the player to start playing then seek back x amount of seconds. Hopefully someone can post a better solution, I'd be happy to clean mine up.

```
while not xbmc.Player().isPlayingVideo():
    xbmc.Monitor().waitForAbort(0.25)

if xbmc.Player().isPlayingVideo():
    start_time = string_to_date(start_time, '%Y-%m-%dT%H:%M:%SZ')
    seek_secs = int((start_time - datetime.utcnow()).total_seconds())
    xbmc.log("seconds seek = " + str(seek_secs))
    xbmc.executebuiltin('Seek(' + str(seek_secs) + ')')
```

**Comment by bigretromike** [comment]
I will check that out, I could estimate how long time did pass, so that should be a problem, but when you start your stream do you have seekbar working or is it always on beginning? 

On August 9, 2019 2:57:53 PM GMT+02:00, eracknaphobia <notifications@github.com> wrote:
>Here's how I handle it in the NHL addon. It's a hack for sure.
>Basically I start the stream then wait for the player to start playing
>then seek back x amount of seconds. Hopefully someone can post a better
>solution, I'd be happy to clean mine up.
>
>```
>while not xbmc.Player().isPlayingVideo():
>    xbmc.Monitor().waitForAbort(0.25)
>
>if xbmc.Player().isPlayingVideo():
>    start_time = string_to_date(start_time, '%Y-%m-%dT%H:%M:%SZ')
>    seek_secs = int((start_time - datetime.utcnow()).total_seconds())
>    xbmc.log("seconds seek = " + str(seek_secs))
>    xbmc.executebuiltin('Seek(' + str(seek_secs) + ')')
>```
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/peak3d/inputstream.adaptive/issues/94#issuecomment-519909189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
@eracknaphobia, for how strange it looks like, your workaround also worked for me. 
I would be very happy if there was official support for function to start from first segment, but until then I will stick with your workaround, thank you very much

**Comment by eracknaphobia** [comment]
@bigretromike You're welcome. The problem I have is I can't just start at first segment because there are hours of "The Game will begin soon" video before the actual event starts. That's why I wrote it this way.

**Comment by bigretromike** [comment]
@eracknaphobia oh, I spoke to soon, it does seek few chunks before earlier.. I could make chunks bigger but then again, by making them smaller I can process them faster. 
It did work flawless at start of the 'live' stream with chunks ~ 10sec that way I could seek back to around 1-2 chunk. 
2 steeps forward, 1 steep behind - thanks anyway

**Comment by glennguy** [comment]
implemented already - `listitem.setProperty('inputstream.adaptive.play_timeshift_buffer', 'true')`

**Comment by eracknaphobia** [comment]
Looks like that code plays from the first segment which doesn't help me out since there are hours of filler segments before the actual content starts. It'd be really nice to have a way to tell it to start at a certain timestamp in the past or i suppose a segment in the past could work too.
