### ISSUE TITLE
SAMPLE-AES support

### ISSUE THREAD

**Issue by Heein** [xbmc/inputstream.adaptive#96]
Is there any plans for SAMPLE-AES support in near future?

Found an implementation for decrypting that kind of decryption stream here @ row 364 https://github.com/selsta/hlsdl/blob/master/src/hls.c

**Comment by peak3d** [comment]
for what container type (ts / mp4) do you need sample-aes?

**Comment by Heein** [comment]
Its mp4 container.

**Comment by peak3d** [comment]
Ok, will add on todo list

**Comment by Heein** [comment]
Awesome!

**Comment by TaMaX83** [comment]
Any update on this one ?

**Comment by c4tz** [comment]
I would also love to decrypt a SAMPLE-AES stream, please make this happen! :)

**Comment by Testato** [comment]
New on Sample-Aes support ?
this is one of the example of transmission that use it.
It is an important Italian Live channel, LA7 Television
https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/Live_960x540_.m3u8

**Comment by glennguy** [comment]
For the record most HLS files that want SAMPLE-AES also have this: `KEYFORMAT="com.apple.streamingkeydelivery"` which is Apple FairPlay. Maybe it's in the realm of possibilities were there a CDM available for iOS that this could bring DRM to that platform, don't hold your breath!

**Comment by CastagnaIT** [comment]
@glennguy can be closed?

**Comment by glennguy** [comment]
Sure
